### ISSUE TITLE
npm run storybook build error

### ISSUE THREAD

**Issue by alamboley** [playcanvas/pcui#155]
**Describe the bug**
Running `npm run storybook` failed

**To Reproduce**
1. Clone project
2. `npm run install`
3. `npm run storybook`

**Screenshots**
```zsh
> @playcanvas/pcui@2.2.6 storybook /Users/aymeric/Downloads/pcui-master
> jsdoc -r -X src > ./.storybook/utils/jsdoc-ast.json && start-storybook -p 9009 -s public

info @storybook/react v6.4.0-beta.27
info 
(node:4180) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-static-dir-flag
info => Loading presets
ERR! Error: Conflict when trying to read staticDirs:
ERR! * Storybook's configuration option: 'staticDirs'
ERR! * Storybook's CLI flag: '--staticDir' or '-s'
ERR! 
ERR! Choose one of them, but not both.
ERR!     at useStatics (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/utils/server-statics.js:50:11)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERR!     at async storybookDevServer (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/dev-server.js:78:3)
ERR!     at async buildDevStandalone (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  Error: Conflict when trying to read staticDirs:
ERR! * Storybook's configuration option: 'staticDirs'
ERR! * Storybook's CLI flag: '--staticDir' or '-s'
ERR! 
ERR! Choose one of them, but not both.
ERR!     at useStatics (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/utils/server-statics.js:50:11)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:93:5)
ERR!     at async storybookDevServer (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/dev-server.js:78:3)
ERR!     at async buildDevStandalone (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)
ERR!     at async buildDev (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5) {
ERR!   stack: 'Error: Conflict when trying to read staticDirs:\n' +
ERR!     "* Storybook's configuration option: 'staticDirs'\n" +
ERR!     "* Storybook's CLI flag: '--staticDir' or '-s'\n" +
ERR!     '\n' +
ERR!     'Choose one of them, but not both.\n' +
ERR!     '    at useStatics (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/utils/server-statics.js:50:11)\n' +
ERR!     '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
ERR!     '    at async storybookDevServer (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/dev-server.js:78:3)\n' +
ERR!     '    at async buildDevStandalone (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/build-dev.js:115:31)\n' +
ERR!     '    at async buildDev (/Users/aymeric/Downloads/pcui-master/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)'
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @playcanvas/pcui@2.2.6 storybook: `jsdoc -r -X src > ./.storybook/utils/jsdoc-ast.json && start-storybook -p 9009 -s public`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @playcanvas/pcui@2.2.6 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aymeric/.npm/_logs/2022-01-27T10_12_47_281Z-debug.log
```

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by ellthompson** [comment]
Hi @alamboley 

I wasn't able to reproduce this locally. Is this still an issue for you? Could I ask what version of node / npm you are running?

**Comment by willeastcott** [comment]
It's reasonably likely that a subsequent update of NPM dependencies has fixed this.

**Comment by alamboley** [comment]
Indeed, I updated my node version and no problem anymore.
