### ISSUE TITLE
Storybook observer example throws error

### ISSUE THREAD

**Issue by Sirahi** [playcanvas/pcui#336]
Storybook observer example throws error when click on Docs or Main in it.

**To Reproduce**
1. Run storybook as explained in [Storybook](https://github.com/playcanvas/pcui?tab=readme-ov-file#storybook) section of readme.
2. After running it, from the left panel, search for observer
3. Click on the observer
4. In the main window, you will see the following call stack instead of observer example working.
5. `Error: Cannot read properties of undefined (reading 'element')
  at new BindingElementToObservers (/src_binding_BindingElementToObservers_index_ts-src_binding_BindingObserversToElement_index_ts-674b9e.iframe.bundle.js:240:1))
  at Main (/examples-Observer-index-stories.iframe.bundle.js:57:16))
  at undecoratedStoryFn (/sb-preview/runtime.js:41:3082))
  at hookified (/sb-preview/runtime.js:7:18507))
  at /sb-preview/runtime.js:41:1912
  at jsxDecorator (/vendors-node_modules_storybook_addon-essentials_dist_actions_preview_js-node_modules_storyboo-2a85ee.iframe.bundle.js:1091:1251))
  at hookified (/sb-preview/runtime.js:7:18507))
  at /sb-preview/runtime.js:41:1451
  at /sb-preview/runtime.js:41:1912`

**Expected behavior**
The observer example should render the example instead of throwing error.

**Screenshots**
![image](https://github.com/playcanvas/pcui/assets/22786724/245c2d5b-fc60-45fc-bc75-ba9830cc4060)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: Chrome Version 120.0.6099.109

**Additional context**
The error is being thrown, because in [src/examples/Observer/index.stories.tsx](https://github.com/playcanvas/pcui/blob/main/src/examples/Observer/index.stories.tsx#L27) the `BindingElementToObservers` expects `args` as an argument.

**Comment by Sirahi** [comment]
Closing this issue as it has been merged.
